routes/web.php
$this->post('password/reset', 'Auth\ResetPasswordController@reset')->name('auth.password.reset');

Route::group(['middleware' => ['auth'], 'prefix' => 'admin', 'as' => 'admin.'], function () {
    Route::get('/home', 'HomeController@index');
    Route::resource('abilities', 'Admin\AbilitiesController');
    Route::post('abilities_mass_destroy', ['uses' => 'Admin\AbilitiesController@massDestroy', 'as' => 'abilities.mass_destroy']);
    Route::resource('roles', 'Admin\RolesController');
    Route::post('roles_mass_destroy', ['uses' => 'Admin\RolesController@massDestroy', 'as' => 'roles.mass_destroy']);
    Route::resource('users', 'Admin\UsersController');
    Route::post('users_mass_destroy', ['uses' => 'Admin\UsersController@massDestroy', 'as' => 'users.mass_destroy']);
    Route::resource('personal', 'Archivos\PersonalController');
    Route::post('personal_mass_destroy', ['uses' => 'Archivos\PersonalController@massDestroy', 'as' => 'personal.mass_destroy']);

    Route::resource('centros', 'Archivos\CentrosController');
    Route::post('centros_mass_destroy', ['uses' => 'Archivos\CentrosController@massDestroy', 'as' => 'centros.mass_destroy']);

    Route::resource('empresas', 'Admin\EmpresasController');
    Route::post('empresas_mass_destroy', ['uses' => 'Archivos\EmpresasController@massDestroy', 'as' => 'empresas.mass_destroy']);

     Route::resource('locales', 'Admin\LocalesController');
    Route::post('localess_mass_destroy', ['uses' => 'Archivos\LocalesController@massDestroy', 'as' => 'localess.mass_destroy']);

    Route::resource('profesionales', 'Archivos\ProfesionalesController');
    Route::post('profesionales_mass_destroy', ['uses' => 'Archivos\ProfesionalesController@massDestroy', 'as' => 'profesionales.mass_destroy']);
    Route::resource('laboratorios', 'Archivos\LaboratoriosController');
    Route::post('laboratorios_mass_destroy', ['uses' => 'Archivos\LaboratoriosController@massDestroy', 'as' => 'laboratorios.mass_destroy']);
    Route::resource('analisis', 'Archivos\AnalisisController');
    Route::post('analisis_mass_destroy', ['uses' => 'Archivos\AnalisisController@massDestroy', 'as' => 'analisis.mass_destroy']);
    Route::resource('sedesafilia', 'Archivos\SedesAfiliaController');
    Route::post('sedesafilia_mass_destroy', ['uses' => 'Archivos\SedesAfiliaController@massDestroy', 'as' => 'sedesafilia.mass_destroy']);
    Route::resource('servicios', 'Archivos\ServiciosController');
    Route::post('servicios_mass_destroy', ['uses' => 'Archivos\ServiciosController@massDestroy', 'as' => 'servicios.mass_destroy']);

    Route::resource('productos', 'Movimientos\ProductosController');
    Route::post('productos_mass_destroy', ['uses' => 'Movimientos\ProductosController@massDestroy', 'as' => 'productos.mass_destroy']);

    Route::resource('ingresos', 'Movimientos\IngresosController');
    Route::post('ingresos_mass_destroy', ['uses' => 'Movimientos\IngresosController@massDestroy', 'as' => 'ingresos.mass_destroy']);

    Route::resource('pacientes', 'Archivos\PacientesController');
    Route::post('pacientes_mass_destroy', ['uses' => 'Archivos\PacientesController@massDestroy', 'as' => 'pacientes.mass_destroy']);


    Route::resource('paquetes', 'Archivos\PaquetesController');
    Route::post('paquetes_mass_destroy', ['uses' => 'Archivos\PaquetesController@massDestroy', 'as' => 'paquetes.mass_destroy']);

    Route::resource('atencion', 'Existencias\AtencionController');
    Route::post('atencion_mass_destroy', ['uses' => 'Existencias\AtencionController@massDestroy', 'as' => 'atencion.mass_destroy']);

    Route::resource('gastos', 'Existencias\GastosController');
    Route::post('gastos_mass_destroy', ['uses' => 'Existencias\GastosController@massDestroy', 'as' => 'gastos.mass_destroy']);
    Route::resource('labporpagar', 'Existencias\LabPorPagarController');
    Route::post('labporpagar_mass_destroy', ['uses' => 'Existencias\LabPorPagarController@massDestroy', 'as' => 'labporpagar.mass_destroy']);

    Route::resource('otrosingresos', 'Existencias\OtrosIngresosController');
    Route::post('otrosingresos_mass_destroy', ['uses' => 'Existencias\OtrosIngresosController@massDestroy', 'as' => 'otrosingresos.mass_destroy']);
    
    Route::resource('resultados', 'Existencias\ResultadosController');
    Route::post('resultados_mass_destroy', ['uses' => 'Existencias\ResultadosController@massDestroy', 'as' => 'resultados.mass_destroy']);

    Route::resource('resultadoslab', 'Existencias\ResultadosLabController');
    Route::post('resultadoslab_mass_destroy', ['uses' => 'Existencias\ResultadosLabController@massDestroy', 'as' => 'resultadoslab.mass_destroy']);

    Route::resource('resultadospaq', 'Existencias\ResultadosPaqController');
    Route::post('resultadospaq_mass_destroy', ['uses' => 'Existencias\ResultadosPaqController@massDestroy', 'as' => 'resultadospaq.mass_destroy']);

    Route::resource('resultadospaqserv', 'Existencias\ResultadosPaqServController');
    Route::post('resultadospaqserv_mass_destroy', ['uses' => 'Existencias\ResultadosPaqServController@massDestroy', 'as' => 'resultadospaqserv.mass_destroy']);

    Route::resource('resultadosguardados', 'Existencias\ResultadosGuardadosController');
    Route::post('resultadosguardados_mass_destroy', ['uses' => 'Existencias\ResultadosGuardadosController@massDestroy', 'as' => 'resultadosguardados.mass_destroy']);

    Route::resource('resultadosguardadoslab', 'Existencias\ResultadosGuardadosLabController');
    Route::post('resultadosguardadoslab_mass_destroy', ['uses' => 'Existencias\ResultadosGuardadosLabController@massDestroy', 'as' => 'resultadosguardadoslab.mass_destroy']);

    Route::resource('resultadosguardadospaq', 'Existencias\ResultadosGuardadosPaqController');
    Route::post('resultadosguardadospaq_mass_destroy', ['uses' => 'Existencias\ResultadosGuardadosPaqController@massDestroy', 'as' => 'resultadosguardadospaq.mass_destroy']);

     Route::resource('resultadosguardadospaqserv', 'Existencias\ResultadosGuardadosPaqServController');
    Route::post('resultadosguardadospaqserv_mass_destroy', ['uses' => 'Existencias\ResultadosGuardadosPaqServController@massDestroy', 'as' => 'resultadosguardadospaqserv.mass_destroy']);

    Route::resource('cuentasporcobrar', 'Existencias\CuentasporCobrarController');
    Route::post('cuentasporcobrar_mass_destroy', ['uses' => 'Existencias\CuentasporCobrarController@massDestroy', 'as' => 'cuentasporcobrar.mass_destroy']);

    Route::resource('comisionesporpagar', 'Existencias\ComisionesPorPagarController');
    Route::post('comisionesporpagar_mass_destroy', ['uses' => 'Existencias\ComisionesPorPagarController@massDestroy', 'as' => 'comisionesporpagar.mass_destroy']);
    Route::resource('comisionespagadas', 'Existencias\ComisionesPagadasController');
    Route::post('comisionespagadas_mass_destroy', ['uses' => 'Existencias\ComisionesPagadasController@massDestroy', 'as' => 'comisionespagadas.mass_destroy']);

    Route::resource('atenciondiaria', 'Reportes\PdfController');
    Route::post('atenciondiaria_mass_destroy', ['uses' => 'Reportes\PdfController@massDestroy', 'as' => 'atenciondiaria.mass_destroy']);
});
    
    Route::get('/paciente/buscar/{dni}', 'Archivos\PacientesController@buscarPacientes');
    Route::get('/existencias/atencion/servbyemp','Archivos\ServiciosController@servbyemp');
    Route::get('/existencias/atencion/paqbyemp','Archivos\PaquetesController@paqbyemp');
    Route::get('/existencias/atencion/perbyemp','Archivos\PersonalController@perbyemp');
    Route::get('/existencias/atencion/probyemp','Archivos\ProfesionalesController@probyemp');
    Route::get('/existencias/atencion/pagoadelantado','Existencias\AtencionController@pagoadelantado');
    Route::get('/existencias/atencion/pagotarjeta','Existencias\AtencionController@pagotarjeta');
    Route::get('/existencias/atencion/dataPacientes/{id}','Existencias\AtencionController@verDataPacientes');
    Route::get('/existencias/atencion/dataServicios/{id}','Existencias\AtencionController@verDataServicios');

    Route::get('/users/locbyemp/{id}','Admin\UsersController@locbyemp');
    Route::get('/pacientes/distbypro/{id}','Archivos\PacientesController@distbypro');



/////// RUTAS DE PACIENTES  ////


    Route::get('/pacientes', function () {return view('pacientes.create');});
    Route::get('/pacientes/create','Archivos\PacientesController@create');
    Route::get('/archivos/pacientes/createmodal', ['uses' => 'Archivos\PacientesController@createmodal', 'as' => 'pacientes.createmodal']);
    Route::post('/pacientes/store', ['uses' => 'Archivos\PacientesController@store', 'as' => 'pacientes.store']);
    Route::post('/pacientes/store2', ['uses' => 'Archivos\PacientesController@store2', 'as' => 'pacientes.store2']);
    Route::get('/pacientes/index',['uses' => 'Archivos\PacientesController@index', 'as' => 'pacientes.index']);
    Route::get('/pacientes/edit/{id}',['uses' => 'Archivos\PacientesController@edit', 'as' => 'pacientes.edit']);
    Route::get('/pacientes/ver/{id}',['uses' => 'Archivos\PacientesController@ver', 'as' => 'pacientes.ver']);
    Route::put('/pacientes/update/{id}',['uses' => 'Archivos\PacientesController@update', 'as' => 'pacientes.update']);
    Route::put('/pacientes/destroy/{id}',['uses' => 'Archivos\PacientesController@destroy', 'as' => 'pacientes.destroy']);
  //  Route::get('/atencion/editar/{id}',['uses' => 'Archivos\PacientesController@edit', 'as' => 'pacientes.edit']);


 Route::put('/comisionesporpagar/destroylab/{id}',['uses' => 'Existencias\ComisionesPorPagarController@destroylab', 'as' => 'comisionesporpagar.destroylab']);



   Route::get('/existencias/atencion/cardainput/{id}','Existencias\AtencionController@cardainput');
   Route::get('/existencias/atencion/cardainput2/{id}','Existencias\AtencionController@cardainput2');
   Route::get('/existencias/atencion/cardainput3/{id}','Existencias\AtencionController@cardainput3');

app/Http/Controllers/Existencias/ComisionesPagadasController.php
<?php

namespace App\Http\Controllers\Existencias;

use App\Atencion;
use App\AtencionDetalle;
use App\AtencionLaboratorio;
use App\AtencionProfesionalesServicio;
use App\AtencionProfesionalesLaboratorio;
use App\Pacientes;
use App\Profesionales;
use App\Analisis;
use App\Debitos;
use App\Empresas;
use App\Locales;
use Carbon\Carbon;
use DB;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\Controller;


class ComisionesPagadasController extends Controller
{
    /**
     * Display a listing of User.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if (! Gate::allows('users_manage')) {
            return abort(401);
        }

        
          $id_usuario = Auth::id();

         $searchUsuarioID = DB::table('users')
                    ->select('*')
                   // ->where('estatus','=','1')
                    ->where('id','=', $id_usuario)
                    ->get();

            foreach ($searchUsuarioID as $usuario) {
                    $usuarioEmp = $usuario->id_empresa;
                    $usuarioSuc = $usuario->id_sucursal;
                }
          

    $f1 = date('YYYY-m-d');
    $f2 = date('YYYY-m-d');

        $f1 = $request->fecha;
        $f2 = $request->fecha2;
        
      
        
        $comisiones_lab_pag = DB::table('atencion_profesionales_laboratorios as a')
        ->select(DB::raw('SUM(a.pagar) as total_lab','id_empresa','a.pagado','a.id_sucursal','a.id','a.created_at as fecha','a.updated_at'))
        ->where('a.id_empresa','=', $usuarioEmp)
        ->where('a.id_sucursal','=', $usuarioSuc)
        ->whereBetween('a.updated_at', [$f1, $f2])
        ->where('a.pagado','=',1)
     //->havingRaw('SUM(a.pagar) > ?', [0])
        ->get();

        $comisiones_serv_pag = DB::table('atencion_profesionales_servicios as a')
        ->select(DB::raw('SUM(a.pagar) as total_serv','id_empresa','a.pagado','a.id_sucursal','a.id','a.created_at as fecha','a.updated_at'))
        ->where('a.id_empresa','=', $usuarioEmp)
        ->where('a.id_sucursal','=', $usuarioSuc)
        ->where('a.pagado','=',1)
        ->whereBetween('a.updated_at', [$f1, $f2])
     //->havingRaw('SUM(a.pagar) > ?', [0])
        ->get();

        $comisiones_lab = DB::table('atencion_profesionales_laboratorios as a')
        ->select('a.id','a.recibo', 'a.id_atencion', 'a.id_laboratorio as id_servicio','a.fecha_pago_comision', 'a.pagado', 'a.porcentaje',
        'a.recibo', 'a.created_at as fecha','a.updated_at', 'a.montolab as costo', 'f.name as nombres',
        'f.apellidos as apellidos', 's.origen', 'p.nombres as pnombres', 'p.apellidos as papellidos')
        ->join('profesionales as f','f.id','a.id_profesional')
        ->join('atencion_detalles as b','a.id_atencion','b.id_atencion')
        ->join('pacientes as p','p.id','b.id_paciente')
        ->join('atencion_laboratorios as s', 'a.id_atencion', 's.id_atencion')
        ->where('a.pagado','=',1)
        ->where('a.id_empresa','=', $usuarioEmp)
        ->where('a.id_sucursal','=', $usuarioSuc)
        ->groupBy('a.recibo')
        ->whereBetween('a.fecha_pago_comision', [$f1, $f2]);
        //->groupBy('recibo');

        $comisionespagadas = DB::table('atencion_profesionales_servicios as a')
        ->select('a.id','a.recibo', 'a.id_atencion', 'a.id_servicio','a.fecha_pago_comision', 'a.pagado', 'a.porcentaje', 'a.recibo', 'a.created_at as fecha','a.updated_at','a.montoser as costo', 'f.name as nombres', 'f.apellidos as apellidos', 's.origen', 'p.nombres as pnombres', 'p.apellidos as papellidos')
        ->join('profesionales as f','f.id','a.id_profesional')
        ->join('atencion_detalles as b','a.id_atencion','b.id_atencion')
        ->join('pacientes as p','p.id','b.id_paciente')
        ->join('atencion_servicios as s', 'a.id_atencion', 's.id_atencion')
        ->where('a.id_empresa','=', $usuarioEmp)
        ->where('a.id_sucursal','=', $usuarioSuc)
        ->where('a.pagado', '=', 1)
        ->whereBetween('a.fecha_pago_comision', [$f1, $f2])
        ->union($comisiones_lab)
        ->groupBy('a.recibo')
        ->get();


        
      
         $comisionespagadas = json_encode($comisionespagadas);
         $comisionespagadas = self::unique_multidim_array(json_decode($comisionespagadas, true), "recibo");

        return view('existencias.comisionespagadas.index', compact('comisionespagadas','f1','comisiones_lab_pag','comisiones_serv_pag'));
    }
 
  static function unique_multidim_array($array, $key) {
    $temp_array = array();
    $i = 0;
    $key_array = array();
   
    foreach($array as $val) {
        if (!in_array($val[$key], $key_array)) {
            $key_array[$i] = $val[$key];
            $temp_array[$i] = $val;
        }
        $i++;
    }
    return $temp_array;
  }     

}

app/Http/Controllers/Existencias/ResultadosGuardadosLabController.php
<?php

namespace App\Http\Controllers\Existencias;
use App\AtencionLaboratorio;
use App\AtencionServicios;
use App\Locales;
use App\Empresas;
use App\RedactarResultados;
use App\AtencionDetalle;
use Carbon\Carbon;
use DB;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\Controller;
use App\Http\Requests\Movimientos\StoreResultadosRequest;
use App\Http\Requests\Movimientos\UpdateResultadosRequest;

class ResultadosGuardadosLabController extends Controller
{
    /**
     * Display a listing of User.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
    	

    	$id_usuario = Auth::id();

    	$searchUsuarioID = DB::table('users')
    	->select('*')
                   // ->where('estatus','=','1')
    	->where('id','=', $id_usuario)
    	->get();

    	foreach ($searchUsuarioID as $usuario) {
    		$usuarioEmp = $usuario->id_empresa;
    		$usuarioSuc = $usuario->id_sucursal;
    	}


    	$f1 = date('YYYY-m-d');
    	$f2 = date('YYYY-m-d');

    	$f1 = $request->fecha;
    	$f2 = $request->fecha2;

    
    	  $laboratorios = DB::table('atencion_profesionales_laboratorios as a')
                ->select('a.id','a.id_atencion','a.id_laboratorio','a.pagado','a.id_empresa','a.id_profesional','a.id_sucursal','a.created_at','d.name as detalleservicio','e.id_paciente','f.nombres','f.apellidos','a.status_redactar_resultados','g.name','g.apellidos as ape')
                ->join('empresas as b','a.id_empresa','b.id')
                ->join('locales as c','a.id_sucursal','c.id')
                ->join('analises as d','a.id_laboratorio','d.id')
                ->join('atencion_detalles as e','a.id_atencion','e.id_atencion')
                ->join('pacientes as f','f.id','e.id_paciente')
                ->join('profesionales as g','g.id','a.id_profesional')
                ->where('a.status_redactar_resultados','=',1)
                ->where('a.id_empresa','=', $usuarioEmp)
                ->where('a.id_sucursal','=', $usuarioSuc)
                ->whereBetween('a.created_at', [$f1, $f2])
                ->orderby('a.created_at','desc')
                ->get();

        


    	return view('existencias.resultadosguardadoslab.index', compact('laboratorios'));
    }

 

}

resources/views/existencias/resultadospaqserv/create.blade.php
@extends('layouts.app')

@section('content')



            {!! Form::open(['method' => 'POST', 'route' => ['admin.resultadospaqserv.store']]) !!}
            {{ Form::hidden('id', $id) }}
<div class="box box-primary">
            <div class="box-header with-border">
              <h3 class="page-title">@lang('global.resultadospaqserv.title')</h3>
            </div>
            <!-- /.box-header -->
            <!-- form start -->
              <div class="box-body">
                <div class="row">
           
                    

                  <div class="container-fluid">
                    @if (!$exists)
                    <textarea class="ckeditor" name="editor1" id="editor1" rows="10" cols="80">

                    </textarea>
                    @else
                    <div class="info-box info-box bg-green">
                      <span class="info-box-icon"><i class="fa fa-comments-o"></i></span>

                      <div class="info-box-content">
                        <span class="info-box-text">El Resultado ya Fue Procesado</span>



                        <span class="progress-description">
                          <h4>


                            {!! $comentario !!}


                          </h4>
                        </span>
                      </div>
                      <!-- /.info-box-content -->
                    </div>
                    @endif

                  </div>
                  
             
        </div>
              </div>
              <!-- /.box-body -->

              <div class="box-footer " style="text-align: right;">
                @if (!$exists)
                     
              {!! Form::submit('GUARDAR', ['class' => 'btn btn-danger']) !!}
                      @endif
              </div>


            
</div>

    @include('partials.javascripts')

@stop

resources/views/existencias/resultadospaqserv/index.blade.php
@inject('request', 'Illuminate\Http\Request')
@extends('layouts.app')

@section('content')
    <h3 class="page-title">@lang('global.resultadospaqserv.title')</h3>
   
      {!! Form::open(['method' => 'get', 'route' => ['admin.resultadospaqserv.index']]) !!}
        <div class="row">
        <div class="col-md-4">
            {!! Form::label('fecha', 'Seleccione una Fecha', ['class' => 'control-label']) !!}
            {!! Form::date('fecha', old('fechanac'), ['id'=>'fecha','class' => 'form-control', 'placeholder' => '', 'required' => '']) !!}
            <p class="help-block"></p>
            @if($errors->has('fecha'))
            <p class="help-block">
                {{ $errors->first('fecha') }}
            </p>
            @endif
        </div>
        <div class="col-md-4">
            {!! Form::submit(trans('global.app_search'), array('class' => 'btn btn-info')) !!}
            {!! Form::close() !!}

        </div>
    </div>

    
  
    <div class="panel panel-default">
        <div class="panel-heading">
            @lang('global.app_list')
        </div>

        <div class="panel-body table-responsive">
            <table class="table table-bordered table-striped {{ count($paquetes) > 0 ? 'datatable' : '' }} dt-select">
                <thead>
                    <tr>
                        <th style="text-align:center;"><input type="checkbox" id="select-all" /></th>
                        <th>Atenciòn</th>
                        <th>Paquete</th>
                        <th>Detalle</th>
                        <th>Paciente</th>
                        <th>Profesional</th>
                        <th>@lang('global.resultadoslab.fields.fecha')</th>
                    
                        <th>&nbsp;</th>

                    </tr>
                </thead>
                
                <tbody>
                    @if (count($paquetes) > 0)
                        @foreach ($paquetes as $paq)
                            <tr data-entry-id="{{ $paq->id }}">
                                <td></td>
                                <td>{{ $paq->id_atencion }}</td>
                                <td>{{ $paq->detalle }}</td>
                                <td>{{ $paq->detalle1 }}</td>
                                <td>{{ $paq->pnombres }},{{ $paq->papellidos }}</td>
                                <td>{{ $paq->nombres }},{{ $paq->apellidos }}</td>
                                <td>{{ $paq->fecha }}</td>

                                <td>
                                    <a href="{{ route('admin.resultadospaqserv.create',['id'=>$paq->id]) }}" class="btn btn-xs btn-info">@lang('global.app_create_resultado')</a>
                                </td>

                            </tr>
                        @endforeach
                    @else
                        <tr>
                            <td colspan="9">@lang('global.app_no_entries_in_table')</td>
                        </tr>
                    @endif
                </tbody>
            </table>
        </div>
    </div>
@stop