routes/web.php
<?php
Route::get('/', function () { return redirect('/admin/home'); });

// Authentication Routes...
$this->get('login', 'Auth\LoginController@showLoginForm')->name('auth.login');
$this->post('login', 'Auth\LoginController@login')->name('auth.login');
$this->post('logout', 'Auth\LoginController@logout')->name('auth.logout');

// Change Password Routes...
$this->get('change_password', 'Auth\ChangePasswordController@showChangePasswordForm')->name('auth.change_password');
$this->patch('change_password', 'Auth\ChangePasswordController@changePassword')->name('auth.change_password');

// Password Reset Routes...
$this->get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('auth.password.reset');
$this->post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('auth.password.reset');
$this->get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
$this->post('password/reset', 'Auth\ResetPasswordController@reset')->name('auth.password.reset');

Route::group(['middleware' => ['auth'], 'prefix' => 'admin', 'as' => 'admin.'], function () {
    Route::get('/home', 'HomeController@index');
    Route::resource('abilities', 'Admin\AbilitiesController');
    Route::post('abilities_mass_destroy', ['uses' => 'Admin\AbilitiesController@massDestroy', 'as' => 'abilities.mass_destroy']);
    Route::resource('roles', 'Admin\RolesController');
    Route::post('roles_mass_destroy', ['uses' => 'Admin\RolesController@massDestroy', 'as' => 'roles.mass_destroy']);
    Route::resource('users', 'Admin\UsersController');
    Route::post('users_mass_destroy', ['uses' => 'Admin\UsersController@massDestroy', 'as' => 'users.mass_destroy']);
    Route::resource('personal', 'Archivos\PersonalController');
    Route::post('personal_mass_destroy', ['uses' => 'Archivos\PersonalController@massDestroy', 'as' => 'personal.mass_destroy']);

    Route::resource('centros', 'Archivos\CentrosController');
    Route::post('centros_mass_destroy', ['uses' => 'Archivos\CentrosController@massDestroy', 'as' => 'centros.mass_destroy']);

    Route::resource('empresas', 'Admin\EmpresasController');
    Route::post('empresas_mass_destroy', ['uses' => 'Archivos\EmpresasController@massDestroy', 'as' => 'empresas.mass_destroy']);

     Route::resource('locales', 'Admin\LocalesController');
    Route::post('localess_mass_destroy', ['uses' => 'Archivos\LocalesController@massDestroy', 'as' => 'localess.mass_destroy']);

    Route::resource('profesionales', 'Archivos\ProfesionalesController');
    Route::post('profesionales_mass_destroy', ['uses' => 'Archivos\ProfesionalesController@massDestroy', 'as' => 'profesionales.mass_destroy']);
    Route::resource('laboratorios', 'Archivos\LaboratoriosController');
    Route::post('laboratorios_mass_destroy', ['uses' => 'Archivos\LaboratoriosController@massDestroy', 'as' => 'laboratorios.mass_destroy']);
    Route::resource('analisis', 'Archivos\AnalisisController');
    Route::post('analisis_mass_destroy', ['uses' => 'Archivos\AnalisisController@massDestroy', 'as' => 'analisis.mass_destroy']);
    Route::resource('sedesafilia', 'Archivos\SedesAfiliaController');
    Route::post('sedesafilia_mass_destroy', ['uses' => 'Archivos\SedesAfiliaController@massDestroy', 'as' => 'sedesafilia.mass_destroy']);
    Route::resource('servicios', 'Archivos\ServiciosController');
    Route::post('servicios_mass_destroy', ['uses' => 'Archivos\ServiciosController@massDestroy', 'as' => 'servicios.mass_destroy']);

    Route::resource('productos', 'Movimientos\ProductosController');
    Route::post('productos_mass_destroy', ['uses' => 'Movimientos\ProductosController@massDestroy', 'as' => 'productos.mass_destroy']);

    Route::resource('ingresos', 'Movimientos\IngresosController');
    Route::post('ingresos_mass_destroy', ['uses' => 'Movimientos\IngresosController@massDestroy', 'as' => 'ingresos.mass_destroy']);

    Route::resource('pacientes', 'Archivos\PacientesController');
    Route::post('pacientes_mass_destroy', ['uses' => 'Archivos\PacientesController@massDestroy', 'as' => 'pacientes.mass_destroy']);


    Route::resource('paquetes', 'Archivos\PaquetesController');
    Route::post('paquetes_mass_destroy', ['uses' => 'Archivos\PaquetesController@massDestroy', 'as' => 'paquetes.mass_destroy']);

    Route::resource('atencion', 'Existencias\AtencionController');
    Route::post('atencion_mass_destroy', ['uses' => 'Existencias\AtencionController@massDestroy', 'as' => 'atencion.mass_destroy']);

    Route::resource('gastos', 'Existencias\GastosController');
    Route::post('gastos_mass_destroy', ['uses' => 'Existencias\GastosController@massDestroy', 'as' => 'gastos.mass_destroy']);
    Route::resource('labporpagar', 'Existencias\LabPorPagarController');
    Route::post('labporpagar_mass_destroy', ['uses' => 'Existencias\LabPorPagarController@massDestroy', 'as' => 'labporpagar.mass_destroy']);

    Route::resource('otrosingresos', 'Existencias\OtrosIngresosController');
    Route::post('otrosingresos_mass_destroy', ['uses' => 'Existencias\OtrosIngresosController@massDestroy', 'as' => 'otrosingresos.mass_destroy']);
    
    Route::resource('resultados', 'Existencias\ResultadosController');
    Route::post('resultados_mass_destroy', ['uses' => 'Existencias\ResultadosController@massDestroy', 'as' => 'resultados.mass_destroy']);

    Route::resource('resultadoslab', 'Existencias\ResultadosLabController');
    Route::post('resultadoslab_mass_destroy', ['uses' => 'Existencias\ResultadosLabController@massDestroy', 'as' => 'resultadoslab.mass_destroy']);

    Route::resource('resultadospaq', 'Existencias\ResultadosPaqController');
    Route::post('resultadospaq_mass_destroy', ['uses' => 'Existencias\ResultadosPaqController@massDestroy', 'as' => 'resultadospaq.mass_destroy']);

    Route::resource('resultadospaqserv', 'Existencias\ResultadosPaqServController');
    Route::post('resultadospaqserv_mass_destroy', ['uses' => 'Existencias\ResultadosPaqServController@massDestroy', 'as' => 'resultadospaqserv.mass_destroy']);

    Route::resource('resultadosguardados', 'Existencias\ResultadosGuardadosController');
    Route::post('resultadosguardados_mass_destroy', ['uses' => 'Existencias\ResultadosGuardadosController@massDestroy', 'as' => 'resultadosguardados.mass_destroy']);

    Route::resource('resultadosguardadoslab', 'Existencias\ResultadosGuardadosLabController');
    Route::post('resultadosguardadoslab_mass_destroy', ['uses' => 'Existencias\ResultadosGuardadosLabController@massDestroy', 'as' => 'resultadosguardadoslab.mass_destroy']);

    Route::resource('resultadosguardadospaq', 'Existencias\ResultadosGuardadosPaqController');
    Route::post('resultadosguardadospaq_mass_destroy', ['uses' => 'Existencias\ResultadosGuardadosPaqController@massDestroy', 'as' => 'resultadosguardadospaq.mass_destroy']);

     Route::resource('resultadosguardadospaqserv', 'Existencias\ResultadosGuardadosPaqServController');
    Route::post('resultadosguardadospaqserv_mass_destroy', ['uses' => 'Existencias\ResultadosGuardadosPaqServController@massDestroy', 'as' => 'resultadosguardadospaqserv.mass_destroy']);

    Route::resource('cuentasporcobrar', 'Existencias\CuentasporCobrarController');
    Route::post('cuentasporcobrar_mass_destroy', ['uses' => 'Existencias\CuentasporCobrarController@massDestroy', 'as' => 'cuentasporcobrar.mass_destroy']);

    Route::resource('comisionesporpagar', 'Existencias\ComisionesPorPagarController');
    Route::post('comisionesporpagar_mass_destroy', ['uses' => 'Existencias\ComisionesPorPagarController@massDestroy', 'as' => 'comisionesporpagar.mass_destroy']);
    Route::resource('comisionespagadas', 'Existencias\ComisionesPagadasController');
    Route::post('comisionespagadas_mass_destroy', ['uses' => 'Existencias\ComisionesPagadasController@massDestroy', 'as' => 'comisionespagadas.mass_destroy']);

    Route::resource('atenciondiaria', 'Reportes\PdfController');
    Route::post('atenciondiaria_mass_destroy', ['uses' => 'Reportes\PdfController@massDestroy', 'as' => 'atenciondiaria.mass_destroy']);
});
    
    Route::get('/paciente/buscar/{dni}', 'Archivos\PacientesController@buscarPacientes');
    Route::get('/existencias/atencion/servbyemp','Archivos\ServiciosController@servbyemp');
    Route::get('/existencias/atencion/paqbyemp','Archivos\PaquetesController@paqbyemp');
    Route::get('/existencias/atencion/perbyemp','Archivos\PersonalController@perbyemp');
    Route::get('/existencias/atencion/probyemp','Archivos\ProfesionalesController@probyemp');
    Route::get('/existencias/atencion/pagoadelantado','Existencias\AtencionController@pagoadelantado');
    Route::get('/existencias/atencion/pagotarjeta','Existencias\AtencionController@pagotarjeta');
    Route::get('/existencias/atencion/dataPacientes/{id}','Existencias\AtencionController@verDataPacientes');
    Route::get('/existencias/atencion/dataServicios/{id}','Existencias\AtencionController@verDataServicios');

    Route::get('/users/locbyemp/{id}','Admin\UsersController@locbyemp');
    Route::get('/pacientes/distbypro/{id}','Archivos\PacientesController@distbypro');



/////// RUTAS DE PACIENTES  ////


    Route::get('/pacientes', function () {return view('pacientes.create');});
    Route::get('/pacientes/create','Archivos\PacientesController@create');
    Route::get('/archivos/pacientes/createmodal', ['uses' => 'Archivos\PacientesController@createmodal', 'as' => 'pacientes.createmodal']);
    Route::post('/pacientes/store', ['uses' => 'Archivos\PacientesController@store', 'as' => 'pacientes.store']);
    Route::post('/pacientes/store2', ['uses' => 'Archivos\PacientesController@store2', 'as' => 'pacientes.store2']);
    Route::get('/pacientes/index',['uses' => 'Archivos\PacientesController@index', 'as' => 'pacientes.index']);
    Route::get('/pacientes/edit/{id}',['uses' => 'Archivos\PacientesController@edit', 'as' => 'pacientes.edit']);

app/Personal.php
<?php
namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Silber\Bouncer\Database\HasRolesAndAbilities;
use Hash;

/**
 * Class Personal
 *
 * @package App
 * @property string $name
 * @property string $apellidos
 * @property string $dni
 * @property string $telefono
 * @property string $email
 * @property string $direccion
*/
class Personal extends Authenticatable
{
    use Notifiable;
    use HasRolesAndAbilities;
   // protected $table = 'public.paquetes_analises';

    protected $fillable = ['name', 'apellidos', 'dni','email', 'telefono','direccion'];
    
        
     public function getNameAndApellidosAttribute()
    {
        return $this->name . ' ' . $this->apellidos;
    }
}

app/Http/Controllers/Archivos/AnalisisController.php
<?php

namespace App\Http\Controllers\Archivos;

use App\Analisis;
use App\Laboratorios;
use App\Empresas;
use App\Locales;
use DB;
use Illuminate\Support\Facades\Auth;
use Silber\Bouncer\Database\Role;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;
use App\Http\Controllers\Controller;
use App\Http\Requests\Archivos\StoreAnalisisRequest;
use App\Http\Requests\Archivos\UpdateAnalisisRequest;

class AnalisisController extends Controller
{
    /**
     * Display a listing of User.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (! Gate::allows('users_manage')) {
            return abort(401);
        }

        $id_usuario = Auth::id();

         $searchUsuarioID = DB::table('users')
                    ->select('*')
                   // ->where('estatus','=','1')
                    ->where('id','=', $id_usuario)
                    ->get();

            foreach ($searchUsuarioID as $usuario) {
                    $usuarioEmp = $usuario->id_empresa;
                    $usuarioSuc = $usuario->id_sucursal;
                }


         $analisis = DB::table('analises as a')
        ->select('a.id','a.name','a.laboratorio','a.preciopublico','a.tiempo','a.material','a.costlab','a.porcentaje','b.nombre','c.nombres','a.id_empresa','a.id_sucursal')
        ->join('empresas as b','a.id_empresa','b.id')
        ->join('locales as c','a.id_sucursal','c.id')
        //->join('laboratorios as d','a.laboratorio','d.name')
        ->where('a.id_empresa','=', $usuarioEmp)
        ->where('a.id_sucursal','=', $usuarioSuc)
        ->orderby('a.created_at','desc')
        ->paginate(5000);

        $laboratorio = Laboratorios::with('name');

        return view('archivos.analisis.index', compact('analisis','laboratorio'));
    }

    /**
     * Show the form for creating new User.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        $id_usuario = Auth::id();

        $searchUsuarioID = DB::table('users')
        ->select('*')
                   // ->where('estatus','=','1')
        ->where('id','=', $id_usuario)
        ->get();

        foreach ($searchUsuarioID as $usuario) {
            $usuarioEmp = $usuario->id_empresa;
            $usuarioSuc = $usuario->id_sucursal;
        }


  
      // $laboratorio = Laboratorios::get()->pluck('name', 'name');

       $laboratorio = DB::table('laboratorios')
        ->select('*')
        ->where('id_empresa','=', $usuarioEmp)
        ->where('id_sucursal','=', $usuarioSuc)
        ->get()->pluck('name','name');

        return view('archivos.analisis.create', compact('laboratorio'));
    }

    /**
     * Store a newly created User in storage.
     *
     * @param  \App\Http\Requests\StoreUsersRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreAnalisisRequest $request)
    {
        if (! Gate::allows('users_manage')) {
            return abort(401);
        }

         $id_usuario = Auth::id();

         $searchUsuarioID = DB::table('users')
                    ->select('*')
                   // ->where('estatus','=','1')
                    ->where('id','=', $id_usuario)
                    ->get();

            foreach ($searchUsuarioID as $usuario) {
                    $usuarioEmp = $usuario->id_empresa;
                    $usuarioSuc = $usuario->id_sucursal;
                }

       $analisis = new Analisis;
       $analisis->name =$request->name;
       $analisis->laboratorio     =$request->laboratorio;
       $analisis->tiempo     =$request->tiempo;
       $analisis->material     =$request->material;
       $analisis->preciopublico     =$request->preciopublico;
       $analisis->costlab     =$request->costlab;
       $analisis->id_empresa= $usuarioEmp;
       $analisis->id_sucursal =$usuarioSuc;
       $analisis->save();


    
       

        return redirect()->route('admin.analisis.index');
    }


    /**
     * Show the form for editing User.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
      
             $id_usuario = Auth::id();

        $searchUsuarioID = DB::table('users')
        ->select('*')
                   // ->where('estatus','=','1')
        ->where('id','=', $id_usuario)
        ->get();

        foreach ($searchUsuarioID as $usuario) {
            $usuarioEmp = $usuario->id_empresa;
            $usuarioSuc = $usuario->id_sucursal;
        }


       $laboratorio = DB::table('laboratorios')
        ->select('*')
        ->where('id_empresa','=', $usuarioEmp)
        ->where('id_sucursal','=', $usuarioSuc)
        ->get()->pluck('name','name');


        $analisis = Analisis::findOrFail($id);
    
        return view('archivos.analisis.edit', compact('analisis', 'laboratorio'));
    }

    /**
     * Update User in storage.
     *
     * @param  \App\Http\Requests\UpdateUsersRequest  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateAnalisisRequest $request, $id)
    {
        if (! Gate::allows('users_manage')) {
            return abort(401);
        }
        $analisis = Analisis::findOrFail($id);
        $analisis->update($request->all());
      
        return redirect()->route('admin.analisis.index');
    }

    /**
     * Remove User from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if (! Gate::allows('users_manage')) {
            return abort(401);
        }
        $analisis = Analisis::findOrFail($id);
        $analisis->delete();

        return redirect()->route('admin.analisis.index');
    }

    /**
     * Delete all selected User at once.
     *
     * @param Request $request
     */
    public function massDestroy(Request $request)
    {
        if (! Gate::allows('users_manage')) {
            return abort(401);
        }
        if ($request->input('ids')) {
            $entries = Analisis::whereIn('id', $request->input('ids'))->get();

            foreach ($entries as $entry) {
                $entry->delete();
            }
        }
    }

}

resources/views/archivos/personal/create.blade.php
@extends('layouts.app')

@section('content')
    <h3 class="page-title">@lang('global.personal.title')</h3>
    {!! Form::open(['method' => 'POST', 'route' => ['admin.personal.store']]) !!}

    <div class="panel panel-default">
        <div class="panel-heading">
            @lang('global.app_create')
        </div>
        
        <div class="panel-body">
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('name', 'Nombres*', ['class' => 'control-label']) !!}
                    {!! Form::text('name', old('name'), ['class' => 'form-control', 'placeholder' => '', 'required' => '']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('name'))
                        <p class="help-block">
                            {{ $errors->first('name') }}
                        </p>
                    @endif
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('apellidos', 'Apellidos', ['class' => 'control-label']) !!}
                    {!! Form::text('apellidos', old('apellidos'), ['class' => 'form-control', 'placeholder' => '', 'required' => '']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('apellidos'))
                        <p class="help-block">
                            {{ $errors->first('apellidos') }}
                        </p>
                    @endif
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('email', 'Email*', ['class' => 'control-label']) !!}
                    {!! Form::email('email', old('email'), ['class' => 'form-control', 'placeholder' => '', 'required' => '']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('email'))
                        <p class="help-block">
                            {{ $errors->first('email') }}
                        </p>
                    @endif
                </div>
            </div>
             <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('dni', 'DNI', ['class' => 'control-label']) !!}
                    {!! Form::text('dni', old('dni'), ['class' => 'form-control', 'placeholder' => '', 'required' => '']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('dni'))
                        <p class="help-block">
                            {{ $errors->first('dni') }}
                        </p>
                    @endif
                </div>
            </div>
             <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('direccion', 'Direciòn', ['class' => 'control-label']) !!}
                    {!! Form::text('direccion', old('direccion'), ['class' => 'form-control', 'placeholder' => '', 'required' => '']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('direccion'))
                        <p class="help-block">
                            {{ $errors->first('direccion') }}
                        </p>
                    @endif
                </div>
            </div>
           <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('telefono', 'Telefono', ['class' => 'control-label']) !!}
                    {!! Form::text('telefono', old('telefono'), ['class' => 'form-control', 'placeholder' => '', 'required' => '']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('telefono'))
                        <p class="help-block">
                            {{ $errors->first('telefono') }}
                        </p>
                    @endif
                </div>
            </div>
          
        </div>
    </div>

    {!! Form::submit(trans('global.app_save'), ['class' => 'btn btn-danger']) !!}
    {!! Form::close() !!}
@stop

resources/views/archivos/personal/edit.blade.php
@extends('layouts.app')

@section('content')
    <h3 class="page-title">@lang('global.personal.title')</h3>
    
    {!! Form::model($personal, ['method' => 'PUT', 'route' => ['admin.personal.update', $personal->id]]) !!}

    <div class="panel panel-default">
        <div class="panel-heading">
            @lang('global.app_edit')
        </div>

        <div class="panel-body">
           <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('name', 'Nombres*', ['class' => 'control-label']) !!}
                    {!! Form::text('name', old('name'), ['class' => 'form-control', 'placeholder' => '', 'required' => '']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('name'))
                        <p class="help-block">
                            {{ $errors->first('name') }}
                        </p>
                    @endif
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('apellidos', 'Apellidos', ['class' => 'control-label']) !!}
                    {!! Form::text('apellidos', old('apellidos'), ['class' => 'form-control', 'placeholder' => '', 'required' => '']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('apellidos'))
                        <p class="help-block">
                            {{ $errors->first('apellidos') }}
                        </p>
                    @endif
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('email', 'Email*', ['class' => 'control-label']) !!}
                    {!! Form::email('email', old('email'), ['class' => 'form-control', 'placeholder' => '', 'required' => '']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('email'))
                        <p class="help-block">
                            {{ $errors->first('email') }}
                        </p>
                    @endif
                </div>
            </div>
             <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('dni', 'DNI', ['class' => 'control-label']) !!}
                    {!! Form::text('dni', old('dni'), ['class' => 'form-control', 'placeholder' => '', 'required' => '']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('dni'))
                        <p class="help-block">
                            {{ $errors->first('dni') }}
                        </p>
                    @endif
                </div>
            </div>
             <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('direccion', 'Direciòn', ['class' => 'control-label']) !!}
                    {!! Form::text('direccion', old('direccion'), ['class' => 'form-control', 'placeholder' => '', 'required' => '']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('direccion'))
                        <p class="help-block">
                            {{ $errors->first('direccion') }}
                        </p>
                    @endif
                </div>
            </div>
           <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('telefono', 'Telefono', ['class' => 'control-label']) !!}
                    {!! Form::text('telefono', old('telefono'), ['class' => 'form-control', 'placeholder' => '', 'required' => '']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('telefono'))
                        <p class="help-block">
                            {{ $errors->first('telefono') }}
                        </p>
                    @endif
                </div>
            </div>
            
        </div>
    </div>

    {!! Form::submit(trans('global.app_update'), ['class' => 'btn btn-danger']) !!}
    {!! Form::close() !!}
@stop

resources/views/archivos/personal/index.blade.php
@inject('request', 'Illuminate\Http\Request')
@extends('layouts.app')

@section('content')
    <h3 class="page-title">@lang('global.personal.title')</h3>
    <p>
        <a href="{{ route('admin.personal.create') }}" class="btn btn-success">@lang('global.app_add_new')</a>
    </p>

    <div class="panel panel-default">
        <div class="panel-heading">
            @lang('global.app_list')
        </div>

        <div class="panel-body table-responsive">
            <table class="table table-bordered table-striped {{ count($personal) > 0 ? 'datatable' : '' }} dt-select">
                <thead>
                    <tr>
                        <th style="text-align:center;"><input type="checkbox" id="select-all" /></th>

                        <th>@lang('global.personal.fields.name')</th>
                        <th>@lang('global.personal.fields.apellidos')</th>
                        <th>@lang('global.personal.fields.dni')</th>
                        <th>@lang('global.personal.fields.telefono')</th>
                        <th>@lang('global.personal.fields.email')</th>
                        <th>@lang('global.personal.fields.direccion')</th>
                        <th>&nbsp;</th>

                    </tr>
                </thead>
                
                <tbody>
                    @if (count($personal) > 0)
                        @foreach ($personal as $prs)
                            <tr data-entry-id="{{ $prs->id }}">
                                <td></td>

                                <td>{{ $prs->name }}</td>
                                <td>{{ $prs->apellidos }}</td>
                                <td>{{ $prs->dni }}</td>
                                <td>{{ $prs->telefono }}</td>
                                <td>{{ $prs->email }}</td>
                                <td>{{ $prs->direccion }}</td>
                                <td>
                                    <a href="{{ route('admin.personal.edit',[$prs->id]) }}" class="btn btn-xs btn-info">@lang('global.app_edit')</a>
                                    {!! Form::open(array(
                                        'style' => 'display: inline-block;',
                                        'method' => 'DELETE',
                                        'onsubmit' => "return confirm('".trans("global.app_are_you_sure")."');",
                                        'route' => ['admin.personal.destroy', $prs->id])) !!}
                                    {!! Form::submit(trans('global.app_delete'), array('class' => 'btn btn-xs btn-danger')) !!}
                                    {!! Form::close() !!}
                                </td>

                            </tr>
                        @endforeach
                    @else
                        <tr>
                            <td colspan="9">@lang('global.app_no_entries_in_table')</td>
                        </tr>
                    @endif
                </tbody>
            </table>
        </div>
    </div>
@stop

@section('javascript') 
    <script>
        window.route_mass_crud_entries_destroy = '{{ route('admin.personal.mass_destroy') }}';
    </script>
@endsection